#
# Ansible の Playbook です。
# GitHub から落としてきた Laravel アプリケーションをローカルコンピューター上にデプロイします。
#
# ※Amazon Linux 専用
#

---
  - hosts: localhost
    become: yes
    become_method: sudo
    tasks:

      - name: remove default Apache
        yum:
            name: httpd-tools22
            state: absent

      - name: remove default Apache
        yum:
            name: httpd22
            state: absent

#     - name: install Apache 2
#       yum:
#           name: httpd24
#           state: latest
#
#     - name: install Apache 2
#       yum:
#           name: httpd24-tools
#           state: latest

      - name: install
        yum:
            name: php70
            state: latest

      - name: install
        yum:
            name: php70-zip
            state: latest

      - name: install
        yum:
            name: php70-mbstring
            state: latest

      - name: install
        yum:
            name: php70-pdo
            state: latest

      - name: install
        yum:
            name: php70-xml
            state: latest

      - name: install
        yum:
            name: mod24_ssl
            state: latest

      - name: Get composer
        get_url:
            url: https://getcomposer.org/installer
            dest: /tmp/installer.php
            mode: 0744

      - name: excute installer
        command: php /tmp/installer.php --install-dir /usr/local/bin/ --filename composer

      - name: erase temporary installer
        file:
            path: /tmp/installer.php
            state: absent

      - name: create /var/www/ directory
        file: dest=/var/www/ state=directory owner=root group=root mode=0755

      - name: create /var/www/laravel.example directory
        file: dest=/var/www/laravel.example state=directory owner=apache group=apache mode=0755

      - name: Cloning Project
        git: >
            dest=/var/www/laravel.example
            repo=https://github.com/aklabo/laravel.example.git
            update=yes
            accept_hostkey=yes
        become: yes
        become_user: apache
        # 毎回 create-project してしまい、APP_KEY が変化するのを防ぐ
        register: cloned
      
      - name: composer create-project
        composer: >
            command=create-project
            working_dir=/var/www/laravel.example
            optimize_autoloader=no
        become: yes
        become_user: apache
        # 毎回 create-project してしまい、APP_KEY が変化するのを防ぐ
        when: cloned|changed
